"""
Conversation persistence (product spec sections 12-13).

The product is a single continuous conversation per user (no multi-chat
UI), so there is effectively one "active" session per user in practice —
but sessions are still keyed by session_id rather than hard-coded to a
singleton, so the shape supports multiple sessions later (or per-test
isolation) without a migration.

A ConversationRecord is what's persisted to disk between process runs. It
stores messages as plain (role, content) pairs rather than LangChain
message objects, since those aren't guaranteed stably JSON-serializable
across langchain-core versions — converting at the runner boundary
(app/agent/runner.py) keeps this module dependency-light and stable.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field


class StoredMessage(BaseModel):
    role: str  # "user" | "assistant"
    content: str


class ConversationRecord(BaseModel):
    session_id: str
    messages: list[StoredMessage] = Field(default_factory=list)
    summary: str = ""

    # Carried through for later phases (5+): which sources are "active" in
    # this conversation, and other analytical/dashboard/report context
    # described in product spec section 12. Present now so the persisted
    # shape doesn't need another migration when those phases land.
    active_source_ids: list[str] = Field(default_factory=list)
    previous_queries: list[str] = Field(default_factory=list)
    dashboard_state: dict | None = None
    report_state: dict | None = None

    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ConversationStore:
    def __init__(self, conversations_dir: Path):
        self._dir = conversations_dir
        self._dir.mkdir(parents=True, exist_ok=True)

    def _path(self, session_id: str) -> Path:
        # session_id is always generated by us (uuid) or a fixed
        # "<user_id>-main" string — never raw, unsanitized user input — so
        # no path-traversal sanitization is attempted here.
        return self._dir / f"{session_id}.json"

    def load(self, session_id: str) -> ConversationRecord:
        path = self._path(session_id)
        if not path.exists():
            return ConversationRecord(session_id=session_id)
        raw = path.read_text(encoding="utf-8").strip()
        if not raw:
            return ConversationRecord(session_id=session_id)
        return ConversationRecord.model_validate(json.loads(raw))

    def save(self, record: ConversationRecord) -> None:
        record.updated_at = datetime.now(timezone.utc)
        self._path(record.session_id).write_text(
            record.model_dump_json(indent=2), encoding="utf-8"
        )

    def delete(self, session_id: str) -> None:
        path = self._path(session_id)
        if path.exists():
            path.unlink()

    def exists(self, session_id: str) -> bool:
        return self._path(session_id).exists()